More tweaks on swtestwait, follow .running if exsits even if there is no JOB ID for some reason.

diff --git a/bin/swtestwait b/bin/swtestwait
--- a/bin/swtestwait
+++ b/bin/swtestwait
@@ -10,7 +10,7 @@ app_dir=`dirname $version_dir`
 app=`basename $app_dir`
 
 #swtest -s -a $app -v $version -b $build 2>&1 | tee test.log
-rm test.log
+rm -f test.log
 swtest -s -a $app -v $version -b $build 2>&1 | tee swtest.out
 
 #-- grep line whose first word is number and assume that's the PBS jobid
@@ -22,59 +22,65 @@ fi
 
 jobid=$(grep "^\w[0-9]" .running)
 if [ $? -ne 0 ]; then
-  echo "Cannot obtain Job ID from .running file. Failing the test."
-  exit -4
+  echo "Cannot obtain Job ID from .running file." 
+  echo "Following .running anyway ..."
+  tail -f .running | read -t 600 line
 fi
 
-#-- Infinite loop to wait until either $jobid runs or ceases to exist
 
-while true; do
+if [[ ! -z $jobid ]]; then
 
-  qstat $jobid &> /dev/null
-  
-  #-- If job is missing for some reason, fail the test
-  if [ $? -ne 0 ]; then
-    echo "Job $jobid is missing or was deleted"
-    echo "Failing this test "
-    rm .running
-    exit -2
-  fi 
-  
-  job_state=$(qstat -f $jobid | grep job_state | awk '{print $3}')
+  #-- Infinite loop to wait until either $jobid runs or ceases to exist
+  while true; do
+
+    qstat $jobid &> /dev/null
+    
+    #-- If job is missing for some reason, fail the test
+    if [ $? -ne 0 ]; then
+      echo "Job $jobid is missing or was deleted"
+      echo "Failing this test "
+      rm .running
+      exit -2
+    fi 
+    
+    job_state=$(qstat -f $jobid | grep job_state | awk '{print $3}')
+    if [ "$job_state" == "R" ]; then
+      echo "Submitted job $jobid is running. Following .running ... "
+      break
+    elif [ "$job_state" == "C" ]; then
+      echo "Submitted job $jobid is completed. "
+      break
+    else
+      echo "Waiting for job $jobid to start ... "
+      sleep 10
+    fi
+
+  done
+
+
   if [ "$job_state" == "R" ]; then
-    echo "Submitted job $jobid is running. Following .running ... "
-    break
-  elif [ "$job_state" == "C" ]; then
-    echo "Submitted job $jobid is completed. "
-    break
-  else
-    echo "Waiting for job $jobid to start ... "
-    sleep 10
+    
+    #-- Start a subshell that check on the existence of .running file 
+    #   && $jobid and terminate when its done. Then we use that subshell PID 
+    #   with "tail" command to let tail follow the output of the test
+    (
+    while true; do
+      qstat $jobid &> /dev/null
+      if [ -e .running ] && [ $? -eq 0 ]; then
+        sleep 30
+      else
+        break
+      fi
+    done
+    ) &
+
+    trackPID=$!
+    tail -f .running --pid=$trackPID
+    
   fi
 
-done
-
-
-if [ "$job_state" == "R" ]; then
+fi
   
-  #-- Start a subshell that check on the existence of .running file 
-  #   && $jobid and terminate when its done. Then we use that subshell PID 
-  #   with "tail" command to let tail follow the output of the test
-  (
-  while true; do
-    qstat $jobid &> /dev/null
-    if [ -e .running ] && [ $? -eq 0 ]; then
-      sleep 30
-    else
-      break
-    fi
-  done
-  ) &
-
-  trackPID=$!
-  tail -f .running --pid=$trackPID
-  
-fi 
 
 #-- Display whatever got recorded to test.log and status file
 echo "Displaying test.log:"
